### Test How 3D Matrices Works

In [5]:
import numpy as np

X = np.random.rand(3,3)
X_res = X.reshape(3,1,3)

assert X_res[0,0,0] == X[0,0], "Wrong"
assert X_res[0,0,1] == X[0,1], "Wrong"
assert X_res[0,0,2] == X[0,2], "Wrong"
assert X_res[1,0,0] == X[1,0], "Wrong"
assert X_res[1,0,1] == X[1,1], "Wrong"
assert X_res[1,0,2] == X[1,2], "Wrong"
assert X_res[2,0,0] == X[2,0], "Wrong"
assert X_res[2,0,1] == X[2,1], "Wrong"
assert X_res[2,0,2] == X[2,2], "Wrong"

```text
Step 1:

(2x2) (2x1) -> (2x1)
*----------* *-----*
| a00, a01 | | b00 |
| a10, a11 | | b01 |
*----------* *-----*

Step 2:
c_ij =  a_ik * b_kj 
*-----------------------*
| a00 * b00 + a01 * b01 |
| a10 * b00 + a11 * b01 |
*-----------------------* 
```

### For 3D Matrix
Given the following:
```python
d1 = 2
d2 = 3
d3 = 4

sample_mat = np.stack( d1 * [ np.arange(1, d2 * d3 + 1).reshape(d2, d3) ]) 
print(sample_mat.shape)
```

This will result to `(d1, d2, d3) == (2, 3, 4)`

In [37]:
d1 = 2
d2 = 3
d3 = 4

sample_mat = np.stack( d1 * [ np.arange(1, d2 * d3 + 1).reshape(d2, d3)])

print((d1, d2, d3) == sample_mat.shape)
assert (d1, d2, d3) == sample_mat.shape, "Wrong"

True


In [38]:
r00 = np.stack( 3 * [ np.arange(1,9).reshape(2,4)])
r01 = np.stack( 2 * [ np.arange(1,13).reshape(3,4)])
r02 = np.stack( 3 * [ np.arange(1,26).reshape(5,5)])

print(r00.shape)
print(r01.shape)
print(r02.shape)

(3, 2, 4)
(2, 3, 4)
(3, 5, 5)


In [45]:
4 * 4 * 4 == 8 * 8

True

In [46]:
X0 = np.arange(0, 2 * 4 * 8).reshape(8, 8)
X1 = X0.reshape(4, 4, 4)

print(X0)

for i in range(0, 4):
    print(X1[i,:,:])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
[[48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]]
