In [2]:
import numpy as np
import matplotlib.pyplot as plt 

In [3]:
y0 = 2 * [1] + 4 * [0]
y1 = 2 * [0] + 2 * [1] + 2 * [0]
y2 = 4 * [0] + 2 * [1]

print(y0)
print(y1)
print(y2)

[1, 1, 0, 0, 0, 0]
[0, 0, 1, 1, 0, 0]
[0, 0, 0, 0, 1, 1]


In [4]:
y_one_hot = np.stack([y0, y1, y2], axis=1)
y_one_hot

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [12]:
# This is it!
num_thresh = 4

y_oh_3d = np.stack(num_thresh * [y_one_hot], axis=1)

page_one = 0
page_two = 1
page_three = 2

print(y_oh_3d.shape)
print('page_one = ', y_oh_3d[:,:, page_one])
print('page_two = ', y_oh_3d[:,:, page_two])
print('page_three = ', y_oh_3d[:,:, page_three])

(6, 4, 3)
page_one =  [[1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
page_two =  [[0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]]
page_three =  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]]


In [14]:
print('y_one_hot.shape = ', y_one_hot.shape)
num_thresh = 4
y_oh_3d = np.stack( num_thresh * [y_one_hot], axis=1)

print(y_oh_3d[:,0,:].shape)
print(y_oh_3d[:,0,:])
print('---------------------')
print(y_oh_3d[:,1,:].shape)
print(y_oh_3d[:,1,:])

print('---------------------')
print(y_oh_3d[:,2, :].shape)
print(y_oh_3d[:,2, :])

print('---------------------')
print(y_oh_3d[:,3, :].shape)
print(y_oh_3d[:,3, :])


y_one_hot.shape =  (6, 3)
(6, 3)
[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
---------------------
(6, 3)
[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
---------------------
(6, 3)
[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
---------------------
(6, 3)
[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
