In [3]:
import numpy as np
import matplotlib.pyplot as plt 

In [4]:
y0 = 2 * [1] + 4 * [0]
y1 = 2 * [0] + 2 * [1] + 2 * [0]
y2 = 4 * [0] + 2 * [1]

print(y0)
print(y1)
print(y2)

[1, 1, 0, 0, 0, 0]
[0, 0, 1, 1, 0, 0]
[0, 0, 0, 0, 1, 1]


In [5]:
y_one_hot = np.stack([y0, y1, y2], axis=1)
y_one_hot

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [14]:
y_oh_3d = y_one_hot.reshape(y_one_hot.shape[0], 1, -1)

page_one = 0
page_two = 1
page_three = 2

print('page_one = ', y_oh_3d[:,0, page_one])
print('page_two = ', y_oh_3d[:,0, page_two])
print('page_three = ', y_oh_3d[:,0, page_three])

page_one =  [1 1 0 0 0 0]
page_two =  [0 0 1 1 0 0]
page_three =  [0 0 0 0 1 1]


In [29]:
num_thresh = 4
y_oh_3d = np.stack( num_thresh * [y_one_hot], axis=1)
# y_oh_3d.shape
# print(y_oh_3d)
# print(y_one_hot)
# print(y_oh_3d)

# print(y_oh_3d.shape)
# y_oh_3d = y_one_hot.reshape(y_one_hot.shape[0], 1, -1)
print(y_oh_3d[:,0,:])
print('---------------------')
print(y_oh_3d[:,1,:])

print('---------------------')
print(y_oh_3d[:,2, :])

print('---------------------')
print(y_oh_3d[:,3, :])


[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
---------------------
[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
---------------------
[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
---------------------
[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
