In [2]:
import numpy as np
import matplotlib.pyplot as plt 

In [3]:
y0 = 2 * [1] + 4 * [0]
y1 = 2 * [0] + 2 * [1] + 2 * [0]
y2 = 4 * [0] + 2 * [1]

print(y0)
print(y1)
print(y2)

[1, 1, 0, 0, 0, 0]
[0, 0, 1, 1, 0, 0]
[0, 0, 0, 0, 1, 1]


In [4]:
y_one_hot = np.stack([y0, y1, y2], axis=1)
y_one_hot

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [20]:
# This is it!
print('y_one_hot.shape = ', y_one_hot.shape)
num_thresh = 4

y_oh_3d = np.stack(num_thresh * [y_one_hot], axis=1)

page_one = 0
page_two = 1
page_three = 2

print('-----------------')
print('page_one.shape =', y_oh_3d[:,:, page_one].shape)
print('page_one = \n', y_oh_3d[:,:, page_one])
print('-----------------')
print('page_two.shape =', y_oh_3d[:,:, page_two].shape)
print('page_two = \n', y_oh_3d[:,:, page_two])
print('-----------------')
print('page_three.shape =', y_oh_3d[:,:, page_three].shape)
print('page_three = \n', y_oh_3d[:,:, page_three])
print('-----------------')

y_one_hot.shape =  (6, 3)
-----------------
page_one.shape = (6, 4)
page_one = 
 [[1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
-----------------
page_two.shape = (6, 4)
page_two = 
 [[0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]]
-----------------
page_three.shape = (6, 4)
page_three = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]]
-----------------


In [29]:
print('y_one_hot.shape = ', y_one_hot.shape)

feat_one = 0
feat_two = 1
feat_three = 2

print('-----------------')
print('feat_one.shape =', y_oh_3d[:,feat_one, :].shape)
print('feat_one = \n', y_oh_3d[:,feat_one, :])

print('-----------------')
print('feat_two.shape =', y_oh_3d[:,feat_two, :].shape)
print('feat_two = \n', y_oh_3d[:,feat_two, :])

print('-----------------')
print('feat_three.shape =', y_oh_3d[:,feat_three, :].shape)
print('feat_three = \n', y_oh_3d[:,feat_three, :])




y_one_hot.shape =  (6, 3)
-----------------
feat_one.shape = (6, 3)
feat_one = 
 [[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
-----------------
feat_two.shape = (6, 3)
feat_two = 
 [[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
-----------------
feat_three.shape = (6, 3)
feat_three = 
 [[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
